version: '3'
services:
  cron:
    build: .
    command: cron -f
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
      - TORII_URL=http://torii-rails:3000/api/v1/enqueue
    networks:
      torii:
        aliases:
          - cron

networks:
  torii:
    external:
      name: torii
